# Generated by Django 2.2 on 2020-03-21 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='attribute',
        ),
    ]
